name: GitHub Pages

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout to gh-pages branch
        uses: actions/checkout@v4

      - name: Generate HTMLs
        run: mvn clean com.ruleoftech:markdown-page-generator-plugin:2.1.0:generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/html